version: 1
disable_existing_loggers: False
log_folder: /Home/Code/game_3/logs/
formatters:
    # https://docs.python.org/3/library/logging.html#logrecord-attributes
    sql_msg:
        format: "%(message)s"
    basic:
        format: "%(created)f - %(name)-12s - %(levelname)-8s - %(message)s"
    simple_error_message:
        format: "%(call_trace)s - Line %(lineno)s - %(ex_only)-20s - '''%(ex)s'''"
    detailed_error_message:
        format: "%(created)f - %(name)-12s - %(levelname)-8s - %(call_trace)s - %(message)s - %(stack)s %(locals)s %(globals)s"
    sanitized_error_message:
        format: "%(created)f - %(filename)-20s - Line %(lineno)-5s -%(ex_only)s"

filters:
    stack_filter:
        (): auxillary.StackContextFilter
    trace_filter:
        (): auxillary.TraceContextFilter
        "base_fnc": "__wrap_log_fnc"

handlers:
    console:
        class: logging.StreamHandler
        level: 1
        formatter: basic
        stream: ext://sys.stdout

    console_err:
        class: logging.StreamHandler
        level: ERROR
        filters: [stack_filter, trace_filter]
        formatter: simple_error_message
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        # filters: [info_special]
        formatter: basic
        filename: info.log
        maxBytes: 5000000
        backupCount: 5
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: basic
        filename: warning.log
        maxBytes: 1000000
        backupCount: 5
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        filters: [stack_filter, trace_filter]
        formatter: simple_error_message
        filename: errors.log
        maxBytes: 5000000
        backupCount: 5
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        filters: [stack_filter, trace_filter]
        formatter: simple_error_message
        filename: critical.log
        maxBytes: 1000000
        backupCount: 5
        encoding: utf8

    detailed_err_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        filters: [stack_filter, trace_filter]
        formatter: detailed_error_message
        filename: detailed_errors.log
        maxBytes: 1000000
        backupCount: 1
        encoding: utf8

    simple_err_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        filters: [stack_filter, trace_filter]
        formatter: simple_error_message
        filename: simple_errors.log
        maxBytes: 1000000
        backupCount: 5
        encoding: utf8

    sanitized_err_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        filters: [stack_filter, trace_filter]
        formatter: sanitized_error_message
        filename: sanitized_errors.log
        maxBytes: 100000
        backupCount: 1
        encoding: utf8

    # sql_handler:
    #     class: interfaces.scribe.SQLiteHandler
    #     level: WARN
    #     filters: [interfaces.scribe.sql_filter]
    #     formatter: sql_msg
    #     database: data.db
    #     table: events
    #     schema: SCHEMA_data.sql
    #     fixtures: FIXTURES_data.sql
    #     row_factory: dict


loggers:
    Aux:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    Objects:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    GUI:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    Iface:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    IfaceScribe:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    Parser:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
    MainApp:
        level: DEBUG
        handlers: [console, info_file_handler, warning_file_handler, error_file_handler, critical_file_handler]
        propagate: no
root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]